In [1]:
import pandas as pd

In [93]:
customers = pd.read_csv("customers.csv")
orders = pd.read_csv("orders.csv")
products = pd.read_csv("products.csv")

orders = orders.merge(products, on='product_id', how='left')
orders['order_date'] = pd.to_datetime(orders['order_date'])

if 'price' not in orders.columns:
    print("Available columns:", orders.columns.tolist())
    raise KeyError("Column 'price' not found. Please check your products.csv structure.")

orders['income'] = orders['price'] * orders['quantity']

repeat_counts = orders['customer_id'].value_counts()
repeating_customers = repeat_counts[repeat_counts > 1]
print(f"Number of repeting customers: {len(repeating_customers)}")

product_order_counts = orders.groupby('product_id')['order_id'].count()
top_product_id = product_order_counts.idxmax()
top_product_name = products.loc[products['product_id'] == top_product_id, 'product_name'].values[0]
print(f"Top seling product: {top_product_name}")

least_product_id = product_order_counts.idxmin()
least_product_name = products.loc[products['product_id'] == least_product_id, 'product_name'].values[0]
print(f"Lest sold product: {least_product_name}")

frequent_visitors = repeat_counts[repeat_counts > 5].index
discount_customers = customers[customers['customer_id'].isin(frequent_visitors)]
print("Customers who should get more discount:")
print(discount_customers[['customer_id', 'name']])

total_income = orders['income'].sum()
print(f"Total income till now: PKR {total_income:,.2f}")

yearly_sales = orders.groupby(orders['order_date'].dt.year)['income'].sum()
print("\nYearly Sale Report:")
print(yearly_sales)

monthly_sales = orders.groupby(orders['order_date'].dt.to_period('M'))['income'].sum()
print("\nMonthly Sale Report:")
print(monthly_sales)

Number of repeting customers: 485
Top seling product: Behind
Lest sold product: First
Customers who should get more discount:
    customer_id     name
1         C0002  William
2         C0003    Ellen
6         C0007    James
7         C0008  Derrick
11        C0012     Todd
..          ...      ...
493       C0494   Kristi
494       C0495   Austin
496       C0497    Susan
498       C0499   Rachel
499       C0500  Jasmine

[202 rows x 2 columns]
Total income till now: PKR 4,134,260.59

Yearly Sale Report:
order_date
2022    1357500.38
2023    1489071.01
2024    1287689.20
Name: income, dtype: float64

Monthly Sale Report:
order_date
2022-01    174606.83
2022-02    131429.46
2022-03    147872.95
2022-04     99819.56
2022-05     74185.19
2022-06    125984.33
2022-07     96078.61
2022-08    102602.68
2022-09     95015.46
2022-10     78645.33
2022-11    133063.62
2022-12     98196.36
2023-01    108926.39
2023-02    100614.27
2023-03    132403.32
2023-04     81954.66
2023-05    159682.07
2023-06    161371.64
2023-07    113853.06
2023-08    122938.18
2023-09     99777.87
2023-10    140647.43
2023-11    134667.98
2023-12    132234.14
2024-01     85660.83
2024-02    145746.19
2024-03     82357.10
2024-04    121439.22
2024-05     94350.64
2024-06    113249.20
2024-07     83719.16
2024-08     82841.26
2024-09    124696.42
2024-10    124655.70
2024-11    113283.46
2024-12    115690.02
Freq: M, Name: income, dtype: float64